version: '3'
services:
  nginx:
    image: nginx:latest
    ports:
      - 443:443
      - 80:80
    volumes:
      - ./docker/nginx/certs/:/etc/nginx/ssl
      - ./docker/nginx/conf.d/default.conf:/etc/nginx/conf.d/default.conf
      - ./:/var/www/api
    networks:
      - app-network
  php:
    build:
      context: .
      dockerfile: ./docker/php/Dockerfile
    volumes:
      - ./:/var/www/api
    networks:
      - app-network
  mysql:
    image: 'mariadb:10.5.8'
    environment:
      MYSQL_ROOT_PASSWORD: "${DB_PASSWORD}"
      MYSQL_USER: "${DB_USERNAME}"
      MYSQL_PASSWORD: "${DB_PASSWORD}"
      MYSQL_DATABASE: "${DB_DATABASE}"
    volumes:
      - mysqldata:/var/lib/mysql
      - ../:/var/www
    networks:
      - app-network
    ports:
      - 3306:3306
  redis:
    image: redis:4.0
    ports:
      - "6382:6379"
    networks:
      - app-network
volumes:
  mysqldata: {}

networks:
  app-network:
    driver: "bridge"
